version: '3'

services:
    nginx-dev:
        build:
            context: .
            dockerfile: docker/Dockerfile
        hostname: nginx-dev
        container_name: nginx-ssl-ja3
        volumes:
            - ./docker/debian-nginx-ssl-ja3/nginx.conf:/usr/local/nginx/conf/nginx.conf:ro
        network_mode: host
        tty: true
        privileged: true
        cap_add:
          - ALL

